version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: crypto-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Redis Service for Caching
  redis:
    image: redis:7
    container_name: crypto-redis
    restart: always
    ports:
      - "6379:6379"

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: crypto-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: crypto-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
